version: '1'
services:
  mongo:
    image: "mongo:4.4.3"
    container_name: board-server
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
  app:
    build: .
    restart: update
    ports:
      - 8083:8083
    depends_on:
      - mongo