spring:
  application:
    name: board-server
  data:
    mongodb:
      uri: mongodb://localhost:27017/bts-board-db
server:
  port: 8083

eureka:
  instance:
    instance-id: board-ms-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/